project_id = "jbsivexwgtjkcyifgmow"

[functions.create-room]
verify_jwt = false

[functions.join-room]
verify_jwt = false

[functions.start-game]
verify_jwt = false

[functions.nominate-chancellor]
verify_jwt = false

[functions.submit-vote]
verify_jwt = false

[functions.herald-discard]
verify_jwt = false

[functions.enact-policy]
verify_jwt = false

[functions.request-veto]
verify_jwt = false

[functions.respond-veto]
verify_jwt = false

[functions.resolve-power]
verify_jwt = false

[functions.reset-room]
verify_jwt = false
